trigger:
  branches:
    include:
    - main
stages:
  - stage: stage_a
    jobs:
      - job: job_a
        steps:
        - pwsh: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]stage_a, job_a value"
          name: setvarStep
        - pwsh: echo $(setvarStep.myOutputVar)
          name: echovar

      - deployment: deployment_a
        environment: env1
        strategy:                  
          runOnce:
            deploy:
              steps:
              - pwsh: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]stage_a, deployment_a value"
                name: setvarStep
              - pwsh: echo $(setvarStep.myOutputVar)
                name: echovar

      
      - job: job_b
        dependsOn: 
        - job_a
        - deployment_a
        variables:
          job_a_variable: $[ dependencies.job_a.outputs['setvarStep.myOutputVar'] ]
          deployment_a_variable: $[ dependencies.deployment_a.outputs['deployment_a.setvarStep.myOutputVar'] ]
        steps:
        - pwsh: |
            'Write-Host "job_a_variable: $(job_a_variable)"'
            'Write-Host "deployment_a_variable: $(deployment_a_variable)"'
          name: Show variables
          
        - pwsh: | 
            echo "##vso[task.setvariable variable=job_a_variable;isOutput=true]$(job_a_variable)"
            echo "##vso[task.setvariable variable=deployment_a_variable;isOutput=true]$(deployment_a_variable)"   
          name: setvarStep

  - stage: stage_b
    dependsOn: stage_a
    jobs:
      - job:
        variables:
          job_a_variable: $[ stageDependencies.stage_a.job_a.outputs['setvarStep.myOutputVar'] ]
          deployment_a_variable: $[ stageDependencies.stage_a.deployment_a.outputs['deployment_a.setvarStep.myOutputVar'] ]
          job_b_variable: $[ stageDependencies.stage_a.job_b.outputs['setvarStep.job_a_variable'] ]
          deployment_b_variable: $[ stageDependencies.stage_a.job_b.outputs['setvarStep.deployment_a_variable'] ]
        steps:
          - pwsh: |
              'Write-Host "Job a variable: $(job_a_variable)"'
              'Write-Host "Deployment a variable: $(deployment_a_variable)"'
              'Write-Host "Job b job a variable: $(job_b_variable)"'
              'Write-Host "Job b Deployment a variable: $(deployment_a_variable)"'
            name: Show variables
            
